In [1]:
%load_ext autoreload
%autoreload 2

import cv2
from pytorchyolo import detect, models

# Load the YOLO model
_, model = models.load_model('./weights/yolo_face_sthanhng.cfg', "./weights/yolo_face_sthanhng.weights")

# Load the image as a numpy array
img = cv2.imread("./images/couple.jpg")
print(img)
# Convert OpenCV bgr to rgb
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Runs the YOLO model on the image 
boxes = detect.detect_image(model, img)

print(boxes)

[[[217 217 217]
  [217 217 217]
  [217 217 217]
  ...
  [241 241 241]
  [241 241 241]
  [241 241 241]]

 [[217 217 217]
  [217 217 217]
  [217 217 217]
  ...
  [241 241 241]
  [241 241 241]
  [241 241 241]]

 [[216 216 216]
  [216 216 216]
  [216 216 216]
  ...
  [241 241 241]
  [241 241 241]
  [241 241 241]]

 ...

 [[204 209 218]
  [196 201 210]
  [188 190 198]
  ...
  [252 250 250]
  [253 251 251]
  [253 251 251]]

 [[206 211 220]
  [202 207 216]
  [197 199 207]
  ...
  [252 250 250]
  [253 251 251]
  [253 251 251]]

 [[205 210 219]
  [206 211 220]
  [205 207 215]
  ...
  [252 250 250]
  [253 251 251]
  [253 251 251]]]
[[ 91.29101    158.21448    187.40686    275.01904      0.99911356
    0.        ]
 [224.90276    137.94994    321.34204    276.4984       0.997505
    0.        ]]
